name: "Frontend Build and Deploy to GCP"

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

env:
  # cache
  CACHE_PATH: /tmp/.buildx-cache-frontend

  # GCP
  REGION: europe-west1 # Update this to your desired region
  GCP_PROJECT_ID: your-gcp-project-id # Update this with your GCP project ID
  GCP_POOL_ID: your-pool-id # Update this with your Workload Identity Pool ID
  GCP_PROVIDER_ID: your-provider-id # Update this with your Workload Identity Provider ID
  GCP_SERVICE_ACCOUNT: your-service_account # Update this with your service account mail address

  # Artifact Registry
  ARTIFACT_REGISTRY: europe-west1-docker.pkg.dev # Change this to your Artifact Registry URL
  ARTIFACT_REPOSITORY: frontend

  # Cloud Run
  SERVICE_NAME: frontend

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ runner.os }}-buildx-frontend-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-frontend

      # - name: Set up Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v0.3.0
      #   with:
      #     project_id: ${{ env.GCP_PROJECT_ID }}
      #     version: "latest"

      - name: Authenticate with OIDC
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: "projects/${{ env.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/${{ env.GCP_POOL_ID }}/providers/${{ env.GCP_PROVIDER_ID }}"
          service_account: "${{ env.GCP_SERVICE_ACCOUNT }}"

      - name: Login to Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.ARTIFACT_REGISTRY }}/${{ env.ARTIFACT_REPOSITORY }}:${{ github.sha }}
          cache-from: type=local,src=${{ env.CACHE_PATH }}
          cache-to: type=local,dest=${{ env.CACHE_PATH }}-new,mode=max

      - name: Move cache
        run: |
          rm -rf ${{ env.CACHE_PATH }}
          mv ${{ env.CACHE_PATH }}-new ${{ env.CACHE_PATH }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.ARTIFACT_REGISTRY }}/${{ env.ARTIFACT_REPOSITORY }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed
